### ISSUE TITLE
Use new seed data where JSON files are used

### ISSUE THREAD

**Issue by connormullett** [slarkbot/slarkbot#59]
A new pattern has been created to use services to fetch data from the slarkbot database. Older constant data (heroes, items, etc) have been stored in large JSON files.

We should rework the commands to use the database accessors rather than searching through JSON

**Comment by cschuijt** [comment]
Fixed in #78 save for the part that'll be fixed when #73 is closed.

**Comment by cschuijt** [comment]
The remaining JSON methods right now are `get_hero_data` and `get_hero_by_name` in helpers.py. I quickly paged through the command files, but they mostly seem to be used in helpers.py themselves. Once we replace those with their database equivalents, we'll have phased out JSON parsing.
